# Generated by Django 4.2.30 on 2026-08-20 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='external_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الجهة الخارجية'),
        ),
        migrations.AddField(
            model_name='document',
            name='issuing_directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_documents', to='core.directorate', verbose_name='المديرية الصادرة عنها (داخلي)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='performed_by_role',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم الدائرة'),
        ),
        migrations.AlterField(
            model_name='directorate',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='اسم المديرية'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='archive/%Y/%m/', verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='الوسم'),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المجلد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='core.department')),
                ('directorate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='core.directorate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='core.folder', verbose_name='المجلد الأب')),
            ],
            options={
                'verbose_name': 'مجلد',
                'verbose_name_plural': 'المجلدات',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.folder', verbose_name='المجلد'),
        ),
    ]
