# Generated by Django 4.2.30 on 2026-08-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_external_entity_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('directorate', 'document_number'), name='unique_document_number_per_directorate', violation_error_message='رقم الوثيقة هذا مستخدم مسبقاً ضمن هذه المديرية.'),
        ),
    ]
