# Generated by Django 4.2.30 on 2026-08-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_unique_document_number_per_directorate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_document_number_per_directorate',
        ),
        migrations.AddField(
            model_name='document',
            name='document_year',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='سنة الوثيقة'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('directorate', 'document_year', 'document_number'), name='unique_document_number_per_directorate_per_year', violation_error_message='رقم الوثيقة هذا مستخدم مسبقاً ضمن هذه المديرية لنفس السنة.'),
        ),
    ]
