# Generated by Django 4.2.30 on 2026-08-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_document_unique_document_number_per_directorate_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='core_auditl_timesta_80074f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['performed_by'], name='core_auditl_perform_508dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['document'], name='core_auditl_documen_3886a9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['document'], name='core_commen_documen_bca4d0_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['created_by'], name='core_commen_created_e4d44d_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='core_custom_role_77f64b_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['directorate'], name='core_custom_directo_dd010f_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['department'], name='core_custom_departm_f1bd0c_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['directorate'], name='core_depart_directo_17e7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['directorate'], name='core_docume_directo_60304d_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['department'], name='core_docume_departm_d3bde4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='core_docume_uploade_8c924b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder'], name='core_docume_folder__032807_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_year'], name='core_docume_documen_888595_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['created_at'], name='core_docume_created_f1aada_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='core_folder_parent__a19e73_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['directorate'], name='core_folder_directo_f21a37_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['department'], name='core_folder_departm_afdc57_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_by'], name='core_folder_created_2d6cc1_idx'),
        ),
    ]
