# Generated by Django 4.2.30 on 2026-08-26 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_core_auditl_timesta_80074f_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+$', 'رقم الوثيقة يجب أن يحتوي على أرقام فقط.')], verbose_name='رقم الوثيقة'),
        ),
    ]
