# Generated by Django 6.0 on 2026-08-27 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_number',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d.*$', 'يجب أن يبدأ رقم الوثيقة برقم.')], verbose_name='رقم الوثيقة'),
        ),
    ]
