# Generated by Django 6.0 on 2026-09-09 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_document_document_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archive/attachments/%Y/%m/', verbose_name='ملف إضافي')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ملف مرفق',
                'verbose_name_plural': 'الملفات المرفقة',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='export_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ التصدير/الختم'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['export_date'], name='core_docume_export__680552_idx'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.document'),
        ),
        migrations.AddField(
            model_name='documentattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
