# Generated by Django 6.0 on 2026-09-10 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_documenttype_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='destination_directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='core.directorate', verbose_name='الجهة المحولة إليها'),
        ),
        migrations.AddField(
            model_name='document',
            name='diwan_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الديوان'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['destination_directorate'], name='core_docume_destina_cabe0f_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['diwan_number'], name='core_docume_diwan_n_cd4d4b_idx'),
        ),
    ]
