# Generated by Django 6.0 on 2026-09-10 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_document_destination_directorate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DestinationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='الجهة المحولة إليها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جهة محولة إليها',
                'verbose_name_plural': 'الجهات المحولة إليها',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_destina_cabe0f_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='destination_entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='core.destinationentity', verbose_name='الجهة المحولة إليها'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['destination_entity'], name='core_docume_destina_18cf32_idx'),
        ),
        migrations.RemoveField(
            model_name='document',
            name='destination_directorate',
        ),
    ]
