# Generated by Django 4.2.30 on 2026-09-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_destinationentity_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_destina_18cf32_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='destination_entity',
        ),
        migrations.AddField(
            model_name='document',
            name='destination_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المحولة إليها'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['destination_entity_name'], name='core_docume_destina_067601_idx'),
        ),
        migrations.DeleteModel(
            name='DestinationEntity',
        ),
    ]
