# Generated by Django 4.2.30 on 2026-09-14 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_document_core_docume_destina_18cf32_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_destina_067601_idx',
        ),
        migrations.AddField(
            model_name='document',
            name='destination_directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_documents', to='core.directorate', verbose_name='الجهة المحولة (داخلي)'),
        ),
        migrations.AddField(
            model_name='document',
            name='destination_type',
            field=models.CharField(blank=True, choices=[('internal', 'داخلي'), ('external', 'خارجي')], max_length=10, null=True, verbose_name='نوع الجهة المحولة'),
        ),
        migrations.AlterField(
            model_name='document',
            name='destination_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المحولة (خارجي)'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['destination_type'], name='core_docume_destina_584a17_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['destination_directorate'], name='core_docume_destina_cabe0f_idx'),
        ),
    ]
