# Generated by Django 4.2.30 on 2026-09-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_document_core_docume_destina_067601_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='اسم الملف الأصلي')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'نسخة سابقة',
                'verbose_name_plural': 'النسخ السابقة',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_destina_584a17_idx',
        ),
        migrations.RemoveIndex(
            model_name='document',
            name='core_docume_destina_cabe0f_idx',
        ),
        migrations.RemoveField(
            model_name='document',
            name='destination_directorate',
        ),
        migrations.RemoveField(
            model_name='document',
            name='destination_type',
        ),
        migrations.AlterField(
            model_name='document',
            name='destination_entity_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الجهة المحولة إليها'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['destination_entity_name'], name='core_docume_destina_067601_idx'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.document', verbose_name='الوثيقة'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_versions', to=settings.AUTH_USER_MODEL, verbose_name='رفعها'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document'], name='core_docume_documen_e467fa_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['uploaded_at'], name='core_docume_uploade_27f162_idx'),
        ),
    ]
