# Generated by Django 4.2.30 on 2026-09-25 12:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_documentversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.models.upload_document_path, verbose_name='الملف'),
        ),
        migrations.AlterField(
            model_name='documentattachment',
            name='file',
            field=models.FileField(upload_to=core.models.upload_attachment_path, verbose_name='ملف إضافي'),
        ),
    ]
