# Generated by Django 6.0 on 2026-10-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_document_file_alter_documentattachment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='حالة الوثيقة'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='core_docume_status_daedd3_idx'),
        ),
    ]
